# Generated by Django 4.2.3 on 2023-07-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_star_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='movie_app.star'),
        ),
    ]
