# Generated by Django 4.2.3 on 2023-07-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_review_stars_delete_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
    ]
