# Generated by Django 4.2.3 on 2023-07-23 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_star_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='stars',
        ),
        migrations.AddField(
            model_name='star',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie_app.star'),
        ),
    ]
