# Generated by Django 4.2.3 on 2023-07-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='star',
            new_name='stars',
        ),
    ]
