# Generated by Django 4.2.3 on 2023-07-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_movie_rating_alter_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
