# Generated by Django 4.2.3 on 2023-07-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_rename_name_director_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='director',
            new_name='name',
        ),
    ]
